repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: make test
        language: system
        pass_filenames: false
      - id: run-lint
        name: Run lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: run-typecheck
        name: Run typecheck
        entry: make typecheck
        language: system
        pass_filenames: false
