name: Unit Tests

on: [push, pull_request]

jobs:
  test37:
    name: Tests 3.7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: pip install -e '.[testing]'
      - name: Run Pytest
        run: make test

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -e '.[testing]'
      - name: Run Pytest
        run: make test
